spring:
  application:
    name: ${WEB_NAME}
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    # Uncomment for local connection
    # url: jdbc:mysql://localhost:3306/invigilator_management_4
    # username: root
    # password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: ${MYSQL_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write timeout: 10000
          connection timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

#JWT Configuration
jwt:
  expirationInMs: ${JWT_EXPIRATION_IN_MS}
  expirationInMsRemember: ${JWT_EXPIRATION_IN_MS_REMEMBER}
  secretKey: ${JWT_SECRET_KEY}

#Server Configuration
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}


  #logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
  
  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  #!!!! Change All Secret Keys And Hide Them Before Deployment !!!!
  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
